# Generated by Django 5.1.2 on 2024-11-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_created_at_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
